name: PR Check

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install uv
          uv venv
          uv sync
          .venv/bin/pip install .[dev]

      - name: Ruff format check
        run: |
          .venv/bin/ruff format --check .

      - name: Run tests
        run: |
          .venv/bin/pytest -q

      - name: Check gitmoji commit
        run: |
          .github/scripts/check_gitmoji.sh
